name = "navigation-site"
compatibility_date = "2023-12-01"

# D1数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "navigation-db"
database_id = "bd874799-c6cc-4c98-a1c4-1bb1921e17f6"

[env.production]
# 生产环境D1数据库绑定
[[env.production.d1_databases]]
binding = "DB"
database_name = "navigation-db"
database_id = "bd874799-c6cc-4c98-a1c4-1bb1921e17f6"

[env.preview]
# 预览环境D1数据库绑定
[[env.preview.d1_databases]]
binding = "DB"
database_name = "navigation-db"
database_id = "bd874799-c6cc-4c98-a1c4-1bb1921e17f6"



 