name = "navigation-site"
compatibility_date = "2023-12-01"

[env.production]
# D1数据库绑定
[[env.production.d1_databases]]
binding = "DB"
database_name = "navigation-db"
database_id = "your-d1-database-id"

[env.preview]
# 预览环境D1数据库绑定
[[env.preview.d1_databases]]
binding = "DB"
database_name = "navigation-db-preview"
database_id = "your-preview-d1-database-id"

# 构建配置
[build]
command = "npm run build"
publish = "out" 