import { useState, useEffect } from "react"
import type { Theme, ThemeClasses } from "@/types"

// 主题样式配置 - 恢复原版样式
const getThemeClasses = (theme: Theme): ThemeClasses => {
  if (theme === "dark") {
    return {
      // 原版深色主题样式
      background: "bg-gradient-to-br from-slate-900 via-blue-900 to-slate-800",
      text: "text-stone-200",
      secondaryText: "text-stone-300", 
      card: "backdrop-blur-md bg-slate-800/20 border-slate-600/30",
      cardBorder: "border-slate-600/30",
      cardHover: "hover:bg-slate-700/30",
      button: "text-stone-200 hover:bg-slate-700/30 border-slate-600/40",
      buttonHover: "hover:bg-slate-700/30",
      input: "bg-slate-800/30 border-slate-600/40 text-stone-200",
      inputFocus: "focus:border-blue-400",
      badge: "bg-slate-700/40 text-stone-300 border-slate-600/40",
      badgeText: "text-stone-300",
      accent: "text-blue-400",
      muted: "text-stone-400",
      overlay: "bg-black/50",
      adminBackground: "bg-slate-800/90",
      adminCard: "backdrop-blur-md bg-slate-800/20 border-slate-600/30",
      adminButton: "bg-slate-600 hover:bg-slate-500",
      adminButtonHover: "hover:bg-slate-500",
      adminText: "text-stone-200",
      adminSecondaryText: "text-stone-300",
      searchBackground: "bg-slate-800/30 border-slate-600/40",
      searchBorder: "border-slate-600/40",
      searchText: "text-stone-200 placeholder:text-stone-400",
      categoryButton: "text-stone-200 hover:bg-slate-700/30 border-slate-600/40",
      categoryButtonHover: "hover:bg-slate-700/30",
      categoryButtonActive: "bg-stone-200 text-slate-800 hover:bg-stone-100",
      categoryButtonText: "text-stone-300",
      recommendedCard: "backdrop-blur-md bg-slate-800/20 border-slate-600/30",
      recommendedCardBorder: "border-slate-600/30",
      recommendedBadge: "bg-gradient-to-r from-blue-600 to-purple-600",
      recommendedBadgeText: "text-white",
      websiteCard: "backdrop-blur-md bg-slate-800/20 border-slate-600/30",
      websiteCardBorder: "border-slate-600/30",
      websiteCardHover: "hover:bg-slate-700/30",
      iconColor: "text-stone-200",
      iconBg: "bg-slate-700/40 group-hover:bg-slate-600/50",
      deleteButton: "bg-red-700 hover:bg-red-600 text-white",
      deleteButtonHover: "hover:bg-red-600",
      editButton: "bg-blue-700 hover:bg-blue-600 text-white",
      editButtonHover: "hover:bg-blue-600",
      saveButton: "bg-green-700 hover:bg-green-600 text-white",
      saveButtonHover: "hover:bg-green-600",
      cancelButton: "bg-gray-600 hover:bg-gray-500 text-white",
      cancelButtonHover: "hover:bg-gray-500",
      addButton: "bg-stone-200 text-slate-800 hover:bg-stone-100",
      addButtonHover: "hover:bg-stone-100",
      themeButton: "text-stone-200 hover:bg-slate-700/30 border-slate-600/40",
      themeButtonHover: "hover:bg-slate-700/30",
      loginButton: "text-stone-200 hover:bg-slate-700/30 border-slate-600/40",
      loginButtonHover: "hover:bg-slate-700/30",
      logoutButton: "text-stone-200 hover:bg-slate-700/30 border-slate-600/40",
      logoutButtonHover: "hover:bg-slate-700/30",
      clearButton: "bg-orange-700 hover:bg-orange-600 text-white",
      clearButtonHover: "hover:bg-orange-600",
      refreshButton: "bg-teal-700 hover:bg-teal-600 text-white",
      refreshButtonHover: "hover:bg-teal-600",
      toggleButton: "bg-indigo-700 hover:bg-indigo-600 text-white",
      toggleButtonHover: "hover:bg-indigo-600",
      dialogBackground: "backdrop-blur-md bg-slate-800/20 border-slate-600/30",
      dialogBorder: "border-slate-600/30",
      dialogText: "text-stone-100",
      dialogSecondaryText: "text-stone-200",
      tabsBackground: "backdrop-blur-md bg-slate-800/20",
      tabsText: "text-stone-400",
      tabsActiveText: "text-stone-200",
      tabsActiveBorder: "border-blue-400",
      radioBackground: "bg-slate-800/30 border-slate-600/40",
      radioText: "text-stone-100",
      radioChecked: "border-blue-400 bg-blue-400",
      checkboxBackground: "bg-slate-800/30 border-slate-600/40",
      checkboxText: "text-stone-100",
      checkboxChecked: "border-blue-400 bg-blue-400",
      selectBackground: "bg-slate-800/30 border-slate-600/40",
      selectText: "text-stone-100",
      selectBorder: "border-slate-600/40",
      textareaBackground: "bg-slate-800/30 border-slate-600/40",
      textareaText: "text-stone-100",
      textareaBorder: "border-slate-600/40",
      labelText: "text-stone-200",
      errorText: "text-red-300",
      successText: "text-green-300",
      warningText: "text-yellow-300",
      infoText: "text-blue-300",
      linkText: "text-blue-400",
      linkHover: "hover:text-blue-300",
      separatorColor: "bg-slate-600",
      scrollbarTrack: "bg-slate-800",
      scrollbarThumb: "bg-slate-600",
      scrollbarThumbHover: "hover:bg-slate-500",
      loadingSpinner: "text-blue-400",
      loadingText: "text-stone-400",
      emptyStateText: "text-stone-400",
      placeholderText: "text-stone-400",
      tooltipBackground: "bg-slate-800 border-slate-600",
      tooltipText: "text-stone-200",
      tooltipBorder: "border-slate-600",
      modalOverlay: "bg-black/80",
      modalBackground: "backdrop-blur-md bg-slate-800/20 border-slate-600/30",
      modalBorder: "border-slate-600/30",
      modalText: "text-stone-200",
      modalSecondaryText: "text-stone-300",
      progressBackground: "bg-slate-700",
      progressFill: "bg-blue-500",
      avatarBackground: "bg-slate-700",
      avatarText: "text-stone-200",
      avatarBorder: "border-slate-600",
      codeBackground: "bg-slate-800 border-slate-600",
      codeText: "text-stone-200",
      codeBorder: "border-slate-600",
      preBackground: "bg-slate-800 border-slate-600",
      preText: "text-stone-200",
      preBorder: "border-slate-600",
      blockquoteBackground: "bg-slate-800 border-slate-600",
      blockquoteText: "text-stone-300",
      blockquoteBorder: "border-slate-600",
      tableBackground: "bg-slate-800",
      tableText: "text-stone-200",
      tableBorder: "border-slate-600",
      tableHeaderBackground: "bg-slate-700",
      tableHeaderText: "text-stone-200",
      tableRowHover: "hover:bg-slate-700",
      tableRowText: "text-stone-200",
      navBackground: "backdrop-blur-md bg-slate-800/20 border-slate-600/30",
      navText: "text-stone-200",
      navBorder: "border-slate-600/30",
      navLinkText: "text-stone-300",
      navLinkHover: "hover:text-stone-200",
      navLinkActive: "text-blue-400",
      sidebarBackground: "bg-slate-900 border-slate-700",
      sidebarText: "text-stone-200",
      sidebarBorder: "border-slate-700",
      sidebarLinkText: "text-stone-300",
      sidebarLinkHover: "hover:text-stone-200",
      sidebarLinkActive: "text-blue-400",
      headerBackground: "backdrop-blur-md bg-slate-800/20 border-slate-600/30",
      headerText: "text-stone-200",
      headerBorder: "border-slate-600/30",
      footerBackground: "bg-slate-900 border-slate-700",
      footerText: "text-stone-200",
      footerBorder: "border-slate-700",
      breadcrumbText: "text-stone-300",
      breadcrumbSeparator: "text-stone-500",
      breadcrumbActive: "text-stone-200",
      paginationBackground: "bg-slate-800 border-slate-600",
      paginationText: "text-stone-200",
      paginationBorder: "border-slate-600",
      paginationHover: "hover:bg-slate-700",
      paginationActive: "bg-blue-700 text-white",
      paginationDisabled: "text-stone-500",
      dropdownBackground: "bg-slate-800 border-slate-600",
      dropdownText: "text-stone-200",
      dropdownBorder: "border-slate-600",
      dropdownItemHover: "hover:bg-slate-700",
      dropdownItemActive: "bg-blue-700 text-white",
      contextMenuBackground: "bg-slate-800 border-slate-600",
      contextMenuText: "text-stone-200",
      contextMenuBorder: "border-slate-600",
      contextMenuItemHover: "hover:bg-slate-700",
      contextMenuItemActive: "bg-blue-700 text-white",
      toastBackground: "bg-slate-800 border-slate-600",
      toastText: "text-stone-200",
      toastBorder: "border-slate-600",
      toastSuccessBackground: "bg-green-800 border-green-600",
      toastSuccessText: "text-green-200",
      toastSuccessBorder: "border-green-600",
      toastErrorBackground: "bg-red-800 border-red-600",
      toastErrorText: "text-red-200",
      toastErrorBorder: "border-red-600",
      toastWarningBackground: "bg-yellow-800 border-yellow-600",
      toastWarningText: "text-yellow-200",
      toastWarningBorder: "border-yellow-600",
      toastInfoBackground: "bg-blue-800 border-blue-600",
      toastInfoText: "text-blue-200",
      toastInfoBorder: "border-blue-600",
      calendarBackground: "bg-slate-800 border-slate-600",
      calendarText: "text-stone-200",
      calendarBorder: "border-slate-600",
      calendarHeaderBackground: "bg-slate-700",
      calendarHeaderText: "text-stone-200",
      calendarDayHover: "hover:bg-slate-700",
      calendarDaySelected: "bg-blue-700 text-white",
      calendarDayToday: "bg-blue-800 text-blue-200",
      calendarDayDisabled: "text-stone-500",
      chartBackground: "bg-slate-800 border-slate-600",
      chartText: "text-stone-200",
      chartBorder: "border-slate-600",
      chartLine: "stroke-blue-400",
      chartFill: "fill-blue-500",
      chartGrid: "stroke-slate-600",
      chartTooltipBackground: "bg-slate-800 border-slate-600",
      chartTooltipText: "text-stone-200",
      chartTooltipBorder: "border-slate-600",
      // 原版特有样式
      textPlaceholder: "placeholder:text-stone-400",
      glass: "backdrop-blur-md bg-slate-800/20 border-slate-600/30",
      glassHover: "hover:bg-slate-700/30"
    }
  } else {
    // 原版浅色主题样式
    return {
      background: "bg-gradient-to-br from-rose-200 via-blue-200 to-amber-100",
      text: "text-slate-700",
      secondaryText: "text-slate-600",
      card: "backdrop-blur-md bg-white/25 border-slate-300/20",
      cardBorder: "border-slate-300/20",
      cardHover: "hover:bg-white/35",
      button: "text-slate-600 hover:bg-white/30 border-slate-300/30",
      buttonHover: "hover:bg-white/30",
      input: "bg-white/40 border-slate-300/30 text-slate-700",
      inputFocus: "focus:border-blue-500",
      badge: "bg-white/30 text-slate-600 border-slate-300/30",
      badgeText: "text-slate-600",
      accent: "text-blue-600",
      muted: "text-slate-500",
      overlay: "bg-black/20",
      adminBackground: "bg-white/90",
      adminCard: "backdrop-blur-md bg-white/25 border-slate-300/20",
      adminButton: "bg-slate-300 hover:bg-slate-400",
      adminButtonHover: "hover:bg-slate-400",
      adminText: "text-slate-700",
      adminSecondaryText: "text-slate-600",
      searchBackground: "bg-white/40 border-slate-300/30",
      searchBorder: "border-slate-300/30",
      searchText: "text-slate-700 placeholder:text-slate-500",
      categoryButton: "text-slate-600 hover:bg-white/30 border-slate-300/30",
      categoryButtonHover: "hover:bg-white/30",
      categoryButtonActive: "bg-slate-600 text-white hover:bg-slate-700",
      categoryButtonText: "text-slate-600",
      recommendedCard: "backdrop-blur-md bg-white/25 border-slate-300/20",
      recommendedCardBorder: "border-slate-300/20",
      recommendedBadge: "bg-gradient-to-r from-blue-500 to-purple-500",
      recommendedBadgeText: "text-white",
      websiteCard: "backdrop-blur-md bg-white/25 border-slate-300/20",
      websiteCardBorder: "border-slate-300/20", 
      websiteCardHover: "hover:bg-white/35",
      iconColor: "text-slate-700",
      iconBg: "bg-white/30 group-hover:bg-white/40",
      deleteButton: "bg-red-500 hover:bg-red-600 text-white",
      deleteButtonHover: "hover:bg-red-600",
      editButton: "bg-blue-500 hover:bg-blue-600 text-white",
      editButtonHover: "hover:bg-blue-600",
      saveButton: "bg-green-500 hover:bg-green-600 text-white",
      saveButtonHover: "hover:bg-green-600",
      cancelButton: "bg-gray-400 hover:bg-gray-500 text-white",
      cancelButtonHover: "hover:bg-gray-500",
      addButton: "bg-slate-600 text-white hover:bg-slate-700",
      addButtonHover: "hover:bg-slate-700",
      themeButton: "text-slate-600 hover:bg-white/30 border-slate-300/30",
      themeButtonHover: "hover:bg-white/30",
      loginButton: "text-slate-600 hover:bg-white/30 border-slate-300/30",
      loginButtonHover: "hover:bg-white/30",
      logoutButton: "text-slate-600 hover:bg-white/30 border-slate-300/30",
      logoutButtonHover: "hover:bg-white/30",
      clearButton: "bg-orange-500 hover:bg-orange-600 text-white",
      clearButtonHover: "hover:bg-orange-600",
      refreshButton: "bg-teal-500 hover:bg-teal-600 text-white",
      refreshButtonHover: "hover:bg-teal-600",
      toggleButton: "bg-indigo-500 hover:bg-indigo-600 text-white",
      toggleButtonHover: "hover:bg-indigo-600",
      dialogBackground: "backdrop-blur-md bg-white/25 border-slate-300/20",
      dialogBorder: "border-slate-300/20",
      dialogText: "text-slate-800",
      dialogSecondaryText: "text-slate-700",
      tabsBackground: "backdrop-blur-md bg-white/25",
      tabsText: "text-slate-500",
      tabsActiveText: "text-slate-700",
      tabsActiveBorder: "border-blue-500",
      radioBackground: "bg-white/40 border-slate-300/30",
      radioText: "text-slate-800",
      radioChecked: "border-blue-500 bg-blue-500",
      checkboxBackground: "bg-white/40 border-slate-300/30",
      checkboxText: "text-slate-800",
      checkboxChecked: "border-blue-500 bg-blue-500",
      selectBackground: "bg-white/40 border-slate-300/30",
      selectText: "text-slate-800",
      selectBorder: "border-slate-300/30",
      textareaBackground: "bg-white/40 border-slate-300/30",
      textareaText: "text-slate-800",
      textareaBorder: "border-slate-300/30",
      labelText: "text-slate-700",
      errorText: "text-red-600",
      successText: "text-green-600",
      warningText: "text-yellow-600",
      infoText: "text-blue-600",
      linkText: "text-blue-600",
      linkHover: "hover:text-blue-700",
      separatorColor: "bg-slate-300",
      scrollbarTrack: "bg-slate-100",
      scrollbarThumb: "bg-slate-400",
      scrollbarThumbHover: "hover:bg-slate-500",
      loadingSpinner: "text-blue-600",
      loadingText: "text-slate-600",
      emptyStateText: "text-slate-500",
      placeholderText: "text-slate-500",
      tooltipBackground: "bg-white border-slate-300",
      tooltipText: "text-slate-700",
      tooltipBorder: "border-slate-300",
      modalOverlay: "bg-black/40",
      modalBackground: "backdrop-blur-md bg-white/25 border-slate-300/20",
      modalBorder: "border-slate-300/20",
      modalText: "text-slate-700",
      modalSecondaryText: "text-slate-600",
      progressBackground: "bg-slate-200",
      progressFill: "bg-blue-500",
      avatarBackground: "bg-slate-200",
      avatarText: "text-slate-700",
      avatarBorder: "border-slate-300",
      codeBackground: "bg-slate-100 border-slate-300",
      codeText: "text-slate-700",
      codeBorder: "border-slate-300",
      preBackground: "bg-slate-100 border-slate-300",
      preText: "text-slate-700",
      preBorder: "border-slate-300",
      blockquoteBackground: "bg-slate-100 border-slate-300",
      blockquoteText: "text-slate-600",
      blockquoteBorder: "border-slate-300",
      tableBackground: "bg-white",
      tableText: "text-slate-700",
      tableBorder: "border-slate-300",
      tableHeaderBackground: "bg-slate-100",
      tableHeaderText: "text-slate-700",
      tableRowHover: "hover:bg-slate-50",
      tableRowText: "text-slate-700",
      navBackground: "backdrop-blur-md bg-white/25 border-slate-300/20",
      navText: "text-slate-700",
      navBorder: "border-slate-300/20",
      navLinkText: "text-slate-600",
      navLinkHover: "hover:text-slate-700",
      navLinkActive: "text-blue-600",
      sidebarBackground: "bg-white border-slate-300",
      sidebarText: "text-slate-700",
      sidebarBorder: "border-slate-300",
      sidebarLinkText: "text-slate-600",
      sidebarLinkHover: "hover:text-slate-700",
      sidebarLinkActive: "text-blue-600",
      headerBackground: "backdrop-blur-md bg-white/25 border-slate-300/20",
      headerText: "text-slate-700",
      headerBorder: "border-slate-300/20",
      footerBackground: "bg-white border-slate-300",
      footerText: "text-slate-700",
      footerBorder: "border-slate-300",
      breadcrumbText: "text-slate-600",
      breadcrumbSeparator: "text-slate-400",
      breadcrumbActive: "text-slate-700",
      paginationBackground: "bg-white border-slate-300",
      paginationText: "text-slate-700",
      paginationBorder: "border-slate-300",
      paginationHover: "hover:bg-slate-50",
      paginationActive: "bg-blue-500 text-white",
      paginationDisabled: "text-slate-400",
      dropdownBackground: "bg-white border-slate-300",
      dropdownText: "text-slate-700",
      dropdownBorder: "border-slate-300",
      dropdownItemHover: "hover:bg-slate-50",
      dropdownItemActive: "bg-blue-500 text-white",
      contextMenuBackground: "bg-white border-slate-300",
      contextMenuText: "text-slate-700",
      contextMenuBorder: "border-slate-300",
      contextMenuItemHover: "hover:bg-slate-50",
      contextMenuItemActive: "bg-blue-500 text-white",
      toastBackground: "bg-white border-slate-300",
      toastText: "text-slate-700",
      toastBorder: "border-slate-300",
      toastSuccessBackground: "bg-green-100 border-green-300",
      toastSuccessText: "text-green-700",
      toastSuccessBorder: "border-green-300",
      toastErrorBackground: "bg-red-100 border-red-300",
      toastErrorText: "text-red-700",
      toastErrorBorder: "border-red-300",
      toastWarningBackground: "bg-yellow-100 border-yellow-300",
      toastWarningText: "text-yellow-700",
      toastWarningBorder: "border-yellow-300",
      toastInfoBackground: "bg-blue-100 border-blue-300",
      toastInfoText: "text-blue-700",
      toastInfoBorder: "border-blue-300",
      calendarBackground: "bg-white border-slate-300",
      calendarText: "text-slate-700",
      calendarBorder: "border-slate-300",
      calendarHeaderBackground: "bg-slate-100",
      calendarHeaderText: "text-slate-700",
      calendarDayHover: "hover:bg-slate-50",
      calendarDaySelected: "bg-blue-500 text-white",
      calendarDayToday: "bg-blue-100 text-blue-700",
      calendarDayDisabled: "text-slate-400",
      chartBackground: "bg-white border-slate-300",
      chartText: "text-slate-700",
      chartBorder: "border-slate-300",
      chartLine: "stroke-blue-500",
      chartFill: "fill-blue-500",
      chartGrid: "stroke-slate-300",
      chartTooltipBackground: "bg-white border-slate-300",
      chartTooltipText: "text-slate-700",
      chartTooltipBorder: "border-slate-300",
      // 原版特有样式
      textMuted: "text-slate-500",
      textPlaceholder: "placeholder:text-slate-500",
      glass: "backdrop-blur-md bg-white/30 border-slate-300/20",
      glassHover: "hover:bg-white/40"
    }
  }
}

// 主题Hook
export function useTheme() {
  const [theme, setTheme] = useState<Theme>("light")
  const [themeClasses, setThemeClasses] = useState<ThemeClasses>(getThemeClasses("light"))

  useEffect(() => {
    // 从localStorage读取主题设置
    const savedTheme = localStorage.getItem("theme") as Theme | null
    if (savedTheme) {
      setTheme(savedTheme)
      setThemeClasses(getThemeClasses(savedTheme))
    }
  }, [])

  const toggleTheme = () => {
    const newTheme = theme === "light" ? "dark" : "light"
    setTheme(newTheme)
    setThemeClasses(getThemeClasses(newTheme))
    localStorage.setItem("theme", newTheme)
  }

  return {
    theme,
    themeClasses,
    toggleTheme
  }
} 
